# **BioASQ Dataset (Medical QA Corpus)**

**Load Data**

In [34]:
import pandas as pd
import json

# df = pd.read_json(r"..\Datasets\BioASQ\training14b.json")
# df

with open(r"..\Datasets\BioASQ\training14b.json", "r", encoding="utf-8") as f:
    data = json.load(f)
data

{'questions': [{'body': 'Is Hirschsprung disease a mendelian or a multifactorial disorder?',
   'documents': ['http://www.ncbi.nlm.nih.gov/pubmed/15858239',
    'http://www.ncbi.nlm.nih.gov/pubmed/15829955',
    'http://www.ncbi.nlm.nih.gov/pubmed/20598273',
    'http://www.ncbi.nlm.nih.gov/pubmed/6650562',
    'http://www.ncbi.nlm.nih.gov/pubmed/12239580',
    'http://www.ncbi.nlm.nih.gov/pubmed/21995290',
    'http://www.ncbi.nlm.nih.gov/pubmed/15617541',
    'http://www.ncbi.nlm.nih.gov/pubmed/23001136',
    'http://www.ncbi.nlm.nih.gov/pubmed/8896569'],
   'ideal_answer': ["Coding sequence mutations in RET, GDNF, EDNRB, EDN3, and SOX10 are involved in the development of Hirschsprung disease. The majority of these genes was shown to be related to Mendelian syndromic forms of Hirschsprung's disease, whereas the non-Mendelian inheritance of sporadic non-syndromic Hirschsprung disease proved to be complex; involvement of multiple loci was demonstrated in a multiplicative model."],
   'concepts': ['http://www.disease-ontology.org/api/metadata/DOID:10487',
    'http://www.nlm.nih.gov/cgi/mesh/2015/MB_cgi?field=uid&exact=Find+Exact+Term&term=D006627',
    'http://www.nlm.nih.gov/cgi/mesh/2015/MB_cgi?field=uid&exact=Find+Exact+Term&term=D020412',
    'http://www.disease-ontology.org/api/metadata/DOID:11372'],
   'type': 'summary',
   'id': '55031181e9bde69634000014',
   'snippets': [{'offsetInBeginSection': 131,
     'offsetInEndSection': 358,
     'text': 'Hirschsprung disease (HSCR) is a multifactorial, non-mendelian disorder in which rare high-penetrance coding sequence mutations in the receptor tyrosine kinase RET contribute to risk in combination with mutations at other genes',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15829955',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 554,
     'offsetInEndSection': 992,
     'text': "In this study, we review the identification of genes and loci involved in the non-syndromic common form and syndromic Mendelian forms of Hirschsprung's disease. The majority of the identified genes are related to Mendelian syndromic forms of Hirschsprung's disease. The non-Mendelian inheritance of sporadic non-syndromic Hirschsprung's disease proved to be complex; involvement of multiple loci was demonstrated in a multiplicative model",
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15617541',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 397,
     'offsetInEndSection': 939,
     'text': 'Coding sequence mutations in e.g. RET, GDNF, EDNRB, EDN3, and SOX10 lead to long-segment (L-HSCR) as well as syndromic HSCR but fail to explain the transmission of the much more common short-segment form (S-HSCR). Furthermore, mutations in the RET gene are responsible for approximately half of the familial and some sporadic cases, strongly suggesting, on the one hand, the importance of non-coding variations and, on the other hand, that additional genes involved in the development of the enteric nervous system still await their discovery',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/12239580',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 941,
     'offsetInEndSection': 1279,
     'text': 'For almost all of the identified HSCR genes incomplete penetrance of the HSCR phenotype has been reported, probably due to modifier loci. Therefore, HSCR has become a model for a complex oligo-/polygenic disorder in which the relationship between different genes creating a non-mendelian inheritance pattern still remains to be elucidated',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/12239580',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 129,
     'offsetInEndSection': 358,
     'text': ' Hirschsprung disease (HSCR) is a multifactorial, non-mendelian disorder in which rare high-penetrance coding sequence mutations in the receptor tyrosine kinase RET contribute to risk in combination with mutations at other genes.',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15829955',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 851,
     'offsetInEndSection': 1007,
     'text': ' The inheritance of Hirschsprung disease is generally consistent with sex-modified multifactorial inheritance with a lower threshold of expression in males.',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/6650562',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 131,
     'offsetInEndSection': 359,
     'text': 'Hirschsprung disease (HSCR) is a multifactorial, non-mendelian disorder in which rare high-penetrance coding sequence mutations in the receptor tyrosine kinase RET contribute to risk in combination with mutations at other genes.',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15829955',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 0,
     'offsetInEndSection': 131,
     'text': 'Differential contributions of rare and common, coding and noncoding Ret mutations to multifactorial Hirschsprung disease liability.',
     'beginSection': 'title',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/20598273',
     'endSection': 'title'},
    {'offsetInBeginSection': 0,
     'offsetInEndSection': 210,
     'text': 'BACKGROUND: RET is the major gene associated to Hirschsprung disease (HSCR) with differential contributions of its rare and common, coding and noncoding mutations to the multifactorial nature of this pathology.',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/21995290',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 151,
     'offsetInEndSection': 376,
     'text': 'In the etiology of Hirschsprung disease various genes play a role; these are: RET, EDNRB, GDNF, EDN3 and SOX10, NTN3, ECE1, Mutations in these genes may result in dominant, recessive or multifactorial patterns of inheritance.',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15858239',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 0,
     'offsetInEndSection': 83,
     'text': "Chromosomal and related Mendelian syndromes associated with Hirschsprung's disease.",
     'beginSection': 'title',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/23001136',
     'endSection': 'title'},
    {'offsetInBeginSection': 715,
     'offsetInEndSection': 818,
     'text': "The majority of the identified genes are related to Mendelian syndromic forms of Hirschsprung's disease",
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15617541',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 151,
     'offsetInEndSection': 375,
     'text': 'In the etiology of Hirschsprung disease various genes play a role; these are: RET, EDNRB, GDNF, EDN3 and SOX10, NTN3, ECE1, Mutations in these genes may result in dominant, recessive or multifactorial patterns of inheritance',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15858239',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 417,
     'offsetInEndSection': 615,
     'text': 'On the basis of a skewed sex-ratio (M/F = 4/1) and a risk to relatives much higher than the incidence in the general population, HSCR has long been regarded as a sex-modified multifactorial disorder',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/8896569',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 858,
     'offsetInEndSection': 1012,
     'text': 'The inheritance of Hirschsprung disease is generally consistent with sex-modified multifactorial inheritance with a lower threshold of expression in males',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/6650562',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 820,
     'offsetInEndSection': 992,
     'text': "The non-Mendelian inheritance of sporadic non-syndromic Hirschsprung's disease proved to be complex; involvement of multiple loci was demonstrated in a multiplicative model",
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15617541',
     'endSection': 'abstract'}]},
  {'body': 'List signaling molecules (ligands) that interact with the receptor EGFR?',
   'documents': ['http://www.ncbi.nlm.nih.gov/pubmed/23959273',
    'http://www.ncbi.nlm.nih.gov/pubmed/21514161',
    'http://www.ncbi.nlm.nih.gov/pubmed/23787814',
    'http://www.ncbi.nlm.nih.gov/pubmed/23888072',
    'http://www.ncbi.nlm.nih.gov/pubmed/23821377',
    'http://www.ncbi.nlm.nih.gov/pubmed/24124521',
    'http://www.ncbi.nlm.nih.gov/pubmed/22260327',
    'http://www.ncbi.nlm.nih.gov/pubmed/24204699',
    'http://www.ncbi.nlm.nih.gov/pubmed/24323361',
    'http://www.ncbi.nlm.nih.gov/pubmed/23089711',
    'http://www.ncbi.nlm.nih.gov/pubmed/23399900',
    'http://www.ncbi.nlm.nih.gov/pubmed/23382875',
    'http://www.ncbi.nlm.nih.gov/pubmed/23729230',
    'http://www.ncbi.nlm.nih.gov/pubmed/23212918',
    'http://www.ncbi.nlm.nih.gov/pubmed/23099994',
    'http://www.ncbi.nlm.nih.gov/pubmed/22247333'],
   'triples': [{'p': 'http://purl.uniprot.org/core/encodedBy',
     's': 'http://purl.uniprot.org/uniprot/Q9QX70',
     'o': 'http://linkedlifedata.com/resource/#_5139515837300022'},
    {'p': 'http://www.w3.org/2004/02/skos/core#prefLabel',
     's': 'http://linkedlifedata.com/resource/#_5139515837300022',
     'o': 'Egfr'},
    {'p': 'http://www.w3.org/2004/02/skos/core#exactMatch',
     's': 'http://purl.uniprot.org/intact/EBI-1256812',
     'o': 'http://purl.uniprot.org/uniprot/Q9QX70'},
    {'p': 'http://www.w3.org/2000/01/rdf-schema#label',
     's': 'http://purl.uniprot.org/intact/EBI-1256812',
     'o': 'Egfr'}],
   'ideal_answer': ['The 7 known EGFR ligands  are: epidermal growth factor (EGF), betacellulin (BTC), epiregulin (EPR), heparin-binding EGF (HB-EGF), transforming growth factor-α [TGF-α], amphiregulin (AREG) and epigen (EPG).'],
   'exact_answer': [['epidermal growth factor'],
    ['betacellulin'],
    ['epiregulin'],
    ['heparin-binding epidermal growth factor'],
    ['transforming growth factor-α'],
    ['amphiregulin'],
    ['epigen']],
   'concepts': ['http://amigo.geneontology.org/cgi-bin/amigo/term_details?term=GO:0005154',
    'http://amigo.geneontology.org/cgi-bin/amigo/term_details?term=GO:0007176',
    'http://amigo.geneontology.org/cgi-bin/amigo/term_details?term=GO:0005488',
    'http://amigo.geneontology.org/cgi-bin/amigo/term_details?term=GO:0042058',
    'http://www.nlm.nih.gov/cgi/mesh/2015/MB_cgi?field=uid&exact=Find+Exact+Term&term=D018773',
    'http://www.nlm.nih.gov/cgi/mesh/2015/MB_cgi?field=uid&exact=Find+Exact+Term&term=D008024',
    'http://amigo.geneontology.org/cgi-bin/amigo/term_details?term=GO:0045741',
    'http://amigo.geneontology.org/cgi-bin/amigo/term_details?term=GO:0007173',
    'http://amigo.geneontology.org/cgi-bin/amigo/term_details?term=GO:0005006',
    'http://amigo.geneontology.org/cgi-bin/amigo/term_details?term=GO:0007175',
    'http://www.uniprot.org/uniprot/EGFR_HUMAN',
    'http://www.uniprot.org/uniprot/EGFR_CHICK'],
   'type': 'list',
   'id': '55046d5ff8aee20f27000007',
   'snippets': [{'offsetInBeginSection': 1085,
     'offsetInEndSection': 1199,
     'text': 'the epidermal growth factor receptor (EGFR) ligands, such as epidermal growth factor (EGF) and amphiregulin (AREG)',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/24323361',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 1139,
     'offsetInEndSection': 1247,
     'text': ' EGFR ligands epidermal growth factor (EGF), amphiregulin (AREG) and transforming growth factor alpha (TGFα)',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/24124521',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 72,
     'offsetInEndSection': 97,
     'text': ' EGFR and its ligand EGF ',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/23959273',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 903,
     'offsetInEndSection': 1058,
     'text': 'Among EGFR ligands, heparin-binding EGF-like growth factor, TGF-α and Betacellulin (BTC) are produced in the tumor microenvironment of FDC-S at RNA level. ',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/23888072',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 322,
     'offsetInEndSection': 493,
     'text': '. Plasma amphiregulin (AR), epidermal growth factor (EGF), transforming growth factor-α, and heparin binding-EGF were assessed by ELISA in 45 chemorefractory mCRC patients',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/23821377',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 346,
     'offsetInEndSection': 414,
     'text': 'Among EGFR ligands, heparin-binding epidermal growth factor (HB-EGF)',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/23787814',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 357,
     'offsetInEndSection': 521,
     'text': ' Of the six known EGFR ligands, transforming growth factor alpha (TGFα) was expressed more highly in triple-negative breast tumors than in tumors of other subtypes.',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/23729230',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 781,
     'offsetInEndSection': 923,
     'text': 'the 7 known EGFR ligands (EGF, betacellulin, epiregulin, heparin-binding EGF, transforming growth factor-α [TGF-α], amphiregulin, and epigen) ',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/23399900',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 1393,
     'offsetInEndSection': 1472,
     'text': 'EGFR ligands based on the two affinity classes: EGF>HB-EGF>TGF-α>BTC>EPR>EPG>AR',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/23382875',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 197,
     'offsetInEndSection': 320,
     'text': 'In this article, however, we demonstrate that PEPD directly binds to and activates epidermal growth factor receptor (EGFR),',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/23212918',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 1559,
     'offsetInEndSection': 1607,
     'text': 'four EGFR ligands (AR, HB-EGF, TGF-α, and EREG) ',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/23099994',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 0,
     'offsetInEndSection': 87,
     'text': 'Epidermal growth factor (EGF) family peptides are ligands for the EGF receptor (EGFR). ',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/22260327',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 240,
     'offsetInEndSection': 490,
     'text': 'oluble amphiregulin (AR), transforming growth factor alpha (TGFα), neuregulin 2 beta, and epigen stimulate greater EGFR coupling to cell proliferation and DNA synthesis than do EGF, betacellulin, heparin-binding EGF-like growth factor, and epiregulin',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/22260327',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 387,
     'offsetInEndSection': 563,
     'text': 'Here, we demonstrate that histamine releases 2 EGFR ligands, amphiregulin and heparin-binding epidermal growth factor-like growth factor (HB-EGF), from airway epithelial cells.',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/22247333',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 72,
     'offsetInEndSection': 231,
     'text': 'mammalian EGFR ligands including EGF, TGF-α (TGFα), amphiregulin (AREG), heparin-binding EGF-like growth factor (HB-EGF), betacellulin, epiregulin, and epigen.',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/21514161',
     'endSection': 'abstract'}]},
  {'body': 'Is the protein Papilin secreted?',
   'documents': ['http://www.ncbi.nlm.nih.gov/pubmed/3320045',
    'http://www.ncbi.nlm.nih.gov/pubmed/7515725',
    'http://www.ncbi.nlm.nih.gov/pubmed/20805556',
    'http://www.ncbi.nlm.nih.gov/pubmed/19297413',
    'http://www.ncbi.nlm.nih.gov/pubmed/19724244',
    'http://www.ncbi.nlm.nih.gov/pubmed/15094122',
    'http://www.ncbi.nlm.nih.gov/pubmed/12666201',
    'http://www.ncbi.nlm.nih.gov/pubmed/21784067',
    'http://www.ncbi.nlm.nih.gov/pubmed/11076767',
    'http://www.ncbi.nlm.nih.gov/pubmed/15094110'],
   'ideal_answer': ['Yes,  papilin is a secreted protein'],
   'exact_answer': 'yes',
   'type': 'yesno',
   'id': '54e25eaaae9738404b000017',
   'snippets': [{'offsetInBeginSection': 1085,
     'offsetInEndSection': 1307,
     'text': 'Using expression analysis, we identify three genes that are transcriptionally regulated by HLH-2: the protocadherin cdh-3, and two genes encoding secreted extracellular matrix proteins, mig-6/papilin and him-4/hemicentin. ',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/21784067',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 226,
     'offsetInEndSection': 458,
     'text': 'We found that mig-6 encodes long (MIG-6L) and short (MIG-6S) isoforms of the extracellular matrix protein papilin, each required for distinct aspects of DTC migration. Both MIG-6 isoforms have a predicted N-terminal papilin cassette',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/19297413',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 1,
     'offsetInEndSection': 111,
     'text': 'apilins are homologous, secreted extracellular matrix proteins which share a common order of protein domains. ',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15094122',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 0,
     'offsetInEndSection': 404,
     'text': 'The TSR superfamily is a diverse family of extracellular matrix and transmembrane proteins, many of which have functions related to regulating matrix organization, cell-cell interactions and cell guidance. This review samples some of the contemporary literature regarding TSR superfamily members (e.g. F-spondin, UNC-5, ADAMTS, papilin, and TRAP) where specific functions are assigned to the TSR domains.',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/15094110',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 0,
     'offsetInEndSection': 43,
     'text': 'Papilins are extracellular matrix proteins ',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/12666201',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 0,
     'offsetInEndSection': 48,
     'text': 'Papilin is an extracellular matrix glycoprotein ',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/11076767',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 731,
     'offsetInEndSection': 882,
     'text': ' Collagen IV, laminin, glutactin, papilin, and other extracellular matrix proteins were made primarily by hemocytes and were secreted into the medium. ',
     'beginSection': 'abstract',
     'document': 'http://www.ncbi.nlm.nih.gov/pubmed/7515725',
     'endSection': 'abstract'},
    {'offsetInBeginSection': 0,
     'offsetInEndSection': 101,

## **Explore Dataset's structure**

**unique keys**

In [35]:
def get_all_keys(d, parent_key=""):
    keys = []
    
    if isinstance(d, dict):
        for k, v in d.items():
            full_key = f"{parent_key}.{k}" if parent_key else k
            keys.append(full_key)
            keys.extend(get_all_keys(v, full_key))
            
    elif isinstance(d, list):
        for i, item in enumerate(d):
            keys.extend(get_all_keys(item, parent_key))
    
    return list(set(keys))

sorted(get_all_keys(data))

['questions',
 'questions._body',
 'questions._type',
 'questions.body',
 'questions.concepts',
 'questions.documents',
 'questions.duplicate_tmp',
 'questions.duplicate_tmp.from',
 'questions.duplicate_tmp.id',
 'questions.duplicate_tmp.type',
 'questions.exact_answer',
 'questions.id',
 'questions.ideal_answer',
 'questions.snippets',
 'questions.snippets.beginSection',
 'questions.snippets.document',
 'questions.snippets.endSection',
 'questions.snippets.offsetInBeginSection',
 'questions.snippets.offsetInEndSection',
 'questions.snippets.text',
 'questions.triples',
 'questions.triples.o',
 'questions.triples.p',
 'questions.triples.s',
 'questions.type']

In [36]:
print("Number of medical QA pairs :", len(data["questions"]))

Number of medical QA pairs : 5729

**Explore mandatory and optional keys**

In [37]:
from collections import Counter

Counter(len(q.keys()) for q in data["questions"])

Counter({7: 3261, 8: 1249, 6: 946, 9: 273})

**mandatory keys (6 keys)**

In [38]:
for q in data["questions"]:
    if len(q.keys()) == 6:
        essential_keys = q.keys()
        break
essential_keys

dict_keys(['body', 'documents', 'ideal_answer', 'type', 'id', 'snippets'])

## **Create CSV Dataset**

In [39]:
df = pd.DataFrame()
json_df = pd.read_json(r"..\Datasets\BioASQ\training14b.json")
json_df

                                              questions
0     {'body': 'Is Hirschsprung disease a mendelian ...
1     {'body': 'List signaling molecules (ligands) t...
2     {'body': 'Is the protein Papilin secreted?', '...
3     {'body': 'Are long non coding RNAs spliced?', ...
4     {'body': 'Is RANKL secreted from the cells?', ...
...                                                 ...
5724  {'body': 'Is Clostridioides difficile an aerob...
5725  {'body': 'Please list the benefits of sodium-g...
5726  {'body': 'Bacteria that most commonly causes u...
5727  {'body': 'Is Bacillus Clausii a probiotic?', '...
5728  {'body': 'Symptoms of chlamydia genital infect...

[5729 rows x 1 columns]

In [40]:
import ast

json_df = pd.json_normalize(json_df.iloc[:, 0], errors='ignore')
json_df.tail(5)

,body,documents,ideal_answer,concepts,type,id,snippets,triples,exact_answer,_body,_type,duplicate_tmp.type,duplicate_tmp.from,duplicate_tmp.id
5724,Is Clostridioides difficile an aerobe or a ana...,"[http://www.ncbi.nlm.nih.gov/pubmed/35131507, ...",[Clostridioides difficile is a strict (obligat...,NaN,factoid,67d71d8f18b1e36f2e00002b,"[{'offsetInBeginSection': 121, 'offsetInEndSec...",NaN,[strict anaerobe],NaN,NaN,NaN,NaN,NaN
5725,Please list the benefits of sodium-glucose cot...,"[http://www.ncbi.nlm.nih.gov/pubmed/29485012, ...","[helps manage type 2 diabetes, promotes weight...",NaN,list,67cdb26a81b1027333000017,"[{'offsetInBeginSection': 1576, 'offsetInEndSe...",NaN,"[[reduce hospitalization], [weight loss], [imp...",NaN,NaN,NaN,NaN,NaN
5726,Bacteria that most commonly causes urinary tra...,"[http://www.ncbi.nlm.nih.gov/pubmed/18703368, ...","[E. coli, Klebsiella spp, Staphylococcus sapro...",NaN,factoid,67e2b0a018b1e36f2e00008b,"[{'offsetInBeginSection': 1010, 'offsetInEndSe...",NaN,[Escherichia coli],NaN,NaN,NaN,NaN,NaN
5727,Is Bacillus Clausii a probiotic?,"[http://www.ncbi.nlm.nih.gov/pubmed/23816335, ...","[Yes, Bacillus Clausii is a spore-forming bact...",NaN,yesno,67e090be18b1e36f2e00006c,"[{'offsetInBeginSection': 0, 'offsetInEndSecti...",NaN,yes,NaN,NaN,NaN,NaN,NaN
5728,Symptoms of chlamydia genital infection in women.,"[http://www.ncbi.nlm.nih.gov/pubmed/36759099, ...",[Symptoms of Chlamydia genital infection in wo...,NaN,list,67d7fded18b1e36f2e000042,"[{'offsetInBeginSection': 0, 'offsetInEndSecti...",NaN,"[[asymptomatic], [lower abdominal discomfort],...",NaN,NaN,NaN,NaN,NaN

In [41]:
json_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5729 entries, 0 to 5728
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   body                5729 non-null   str
 1   documents           5729 non-null   object
 2   ideal_answer        5729 non-null   object
 3   concepts            1854 non-null   object
 4   type                5729 non-null   str
 5   id                  5729 non-null   str
 6   snippets            5729 non-null   object
 7   triples             322 non-null    object
 8   exact_answer        4366 non-null   object
 9   _body               18 non-null     str
 10  _type               17 non-null     str
 11  duplicate_tmp.type  1 non-null      float64
 12  duplicate_tmp.from  1 non-null      str
 13  duplicate_tmp.id    1 non-null      object
dtypes: float64(1), object(7), str(6)
memory usage: 1.1+ MB

In [42]:
type(json_df["ideal_answer"].iloc[0])

list

In [43]:
df["question"] = json_df["body"]
df["answer"] = json_df["ideal_answer"].apply(lambda x: x[0])
df["type"] = json_df["type"]

def process_answer(row):
    if row["type"] == "list":
        return " | ".join(i[0] for i in row["exact_answer"])
    elif row["type"] == "factoid":
        return row["exact_answer"][0]
    elif row["type"] == "yesno":
        return row["exact_answer"]
    else:
        return None

df["exact_answer"] = json_df.apply(process_answer, axis=1)

def process_snippets(snippets):
    extracted_context = ""
    for snippet in snippets:
        snip_text = snippet["text"]
        snip_text = snip_text.strip()
        extracted_context += snip_text + "\n"
    return extracted_context

df["context"] = json_df["snippets"].apply(process_snippets)
df = df[["context", "question", "answer", "exact_answer", "type"]]
df

,context,question,answer,exact_answer,type
0,Hirschsprung disease (HSCR) is a multifactoria...,Is Hirschsprung disease a mendelian or a multi...,"Coding sequence mutations in RET, GDNF, EDNRB,...",NaN,summary
1,the epidermal growth factor receptor (EGFR) li...,List signaling molecules (ligands) that intera...,The 7 known EGFR ligands are: epidermal growt...,epidermal growth factor | betacellulin | epire...,list
2,"Using expression analysis, we identify three g...",Is the protein Papilin secreted?,"Yes, papilin is a secreted protein",yes,yesno
3,Our analyses indicate that lncRNAs are generat...,Are long non coding RNAs spliced?,Long non coding RNAs appear to be spliced thro...,yes,yesno
4,Osteoprotegerin (OPG) is a soluble secreted fa...,Is RANKL secreted from the cells?,Receptor activator of nuclear factor κB ligand...,yes,yesno
...,...,...,...,...,...
5724,strictly anaerobic bacterium\nClostridioides d...,Is Clostridioides difficile an aerobe or a ana...,Clostridioides difficile is a strict (obligate...,strict anaerobe,factoid
5725,Glucagon antagonism enhances the therapeutic e...,Please list the benefits of sodium-glucose cot...,"helps manage type 2 diabetes, promotes weight ...",reduce hospitalization | weight loss | improve...,list
5726,Escherichia coli was the most identified uropa...,Bacteria that most commonly causes urinary tra...,"E. coli, Klebsiella spp, Staphylococcus saprop...",Escherichia coli,factoid
5727,Bacillus clausii is a commercial spore probiot...,Is Bacillus Clausii a probiotic?,"Yes, Bacillus Clausii is a spore-forming bacte...",yes,yesno
5728,Some women infected with Chlamydia trachomatis...,Symptoms of chlamydia genital infection in women.,Symptoms of Chlamydia genital infection in wom...,asymptomatic | lower abdominal discomfort | sa...,list

In [44]:
print(df["context"].iloc[0])

Hirschsprung disease (HSCR) is a multifactorial, non-mendelian disorder in which rare high-penetrance coding sequence mutations in the receptor tyrosine kinase RET contribute to risk in combination with mutations at other genes
In this study, we review the identification of genes and loci involved in the non-syndromic common form and syndromic Mendelian forms of Hirschsprung's disease. The majority of the identified genes are related to Mendelian syndromic forms of Hirschsprung's disease. The non-Mendelian inheritance of sporadic non-syndromic Hirschsprung's disease proved to be complex; involvement of multiple loci was demonstrated in a multiplicative model
Coding sequence mutations in e.g. RET, GDNF, EDNRB, EDN3, and SOX10 lead to long-segment (L-HSCR) as well as syndromic HSCR but fail to explain the transmission of the much more common short-segment form (S-HSCR). Furthermore, mutations in the RET gene are responsible for approximately half of the familial and some sporadic cases, strongly suggesting, on the one hand, the importance of non-coding variations and, on the other hand, that additional genes involved in the development of the enteric nervous system still await their discovery
For almost all of the identified HSCR genes incomplete penetrance of the HSCR phenotype has been reported, probably due to modifier loci. Therefore, HSCR has become a model for a complex oligo-/polygenic disorder in which the relationship between different genes creating a non-mendelian inheritance pattern still remains to be elucidated
Hirschsprung disease (HSCR) is a multifactorial, non-mendelian disorder in which rare high-penetrance coding sequence mutations in the receptor tyrosine kinase RET contribute to risk in combination with mutations at other genes.
The inheritance of Hirschsprung disease is generally consistent with sex-modified multifactorial inheritance with a lower threshold of expression in males.
Hirschsprung disease (HSCR) is a multifactorial, non-mendelian disorder in which rare high-penetrance coding sequence mutations in the receptor tyrosine kinase RET contribute to risk in combination with mutations at other genes.
Differential contributions of rare and common, coding and noncoding Ret mutations to multifactorial Hirschsprung disease liability.
BACKGROUND: RET is the major gene associated to Hirschsprung disease (HSCR) with differential contributions of its rare and common, coding and noncoding mutations to the multifactorial nature of this pathology.
In the etiology of Hirschsprung disease various genes play a role; these are: RET, EDNRB, GDNF, EDN3 and SOX10, NTN3, ECE1, Mutations in these genes may result in dominant, recessive or multifactorial patterns of inheritance.
Chromosomal and related Mendelian syndromes associated with Hirschsprung's disease.
The majority of the identified genes are related to Mendelian syndromic forms of Hirschsprung's disease
In the etiology of Hirschsprung disease various genes play a role; these are: RET, EDNRB, GDNF, EDN3 and SOX10, NTN3, ECE1, Mutations in these genes may result in dominant, recessive or multifactorial patterns of inheritance
On the basis of a skewed sex-ratio (M/F = 4/1) and a risk to relatives much higher than the incidence in the general population, HSCR has long been regarded as a sex-modified multifactorial disorder
The inheritance of Hirschsprung disease is generally consistent with sex-modified multifactorial inheritance with a lower threshold of expression in males
The non-Mendelian inheritance of sporadic non-syndromic Hirschsprung's disease proved to be complex; involvement of multiple loci was demonstrated in a multiplicative model

In [45]:
df.to_csv(r"..\Datasets\BioASQ\bioasq_dataset.csv", index=False)